CREATE DATABASE IF NOT EXISTS golang;

USE golang;

DROP TABLE IF EXISTS publicacoes;
DROP TABLE IF EXISTS seguidores;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    nick VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(64) NOT NULL,
    criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB, CHARSET=UTF8;


CREATE TABLE seguidores(
    usuario_id INT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    seguidor_id INT NOT NULL,
    FOREIGN KEY (seguidor_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, seguidor_id)
) ENGINE=INNODB, CHARSET=UTF8;

CREATE TABLE publicacoes(
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    conteudo VARCHAR(300) NOT NULL,
    autor_id INT NOT NULL,
    FOREIGN KEY (autor_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    curtidas INT NOT NULL DEFAULT 0,
    criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB, CHARSET=UTF8;