CREATE IF NOT EXISTS DATABASE golang;

USE golang;

DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    nick VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(64) NOT NULL,
    criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB, CHARSET=UTF8;